export const SEARCH_PROFILES_PENDING = "SEARCH_PROFILES_PENDING";
export const SEARCH_PROFILES_REJECTED = "SEARCH_PROFILES_REJECTED";
export const SEARCH_PROFILES_FULFILLED = "SEARCH_PROFILES_FULFILLED";

export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";
