export const LOGIN = 'LOGIN'
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED'
export const LOGIN_REJECTED = 'LOGIN_REJECTED'

export const LOGOUT = 'LOGOUT'

export const EDIT_PROFILE = 'EDIT_PROFILE'
export const EDIT_PROFILE_PENDING = 'EDIT_PROFILE_LOGIN_PENDING'
export const EDIT_PROFILE_FULFILLED = 'EDIT_PROFILE_LOGIN_FULFILLED'
export const EDIT_PROFILE_REJECTED = 'EDIT_PROFILE_LOGIN_REJECTED'
