export const LOGIN = "LOGIN";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const LOGOUT = "LOGOUT";

export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_PENDING = "EDIT_PROFILE_LOGIN_PENDING";
export const EDIT_PROFILE_FULFILLED = "EDIT_PROFILE_LOGIN_FULFILLED";
export const EDIT_PROFILE_REJECTED = "EDIT_PROFILE_LOGIN_REJECTED";

export const SEARCH = "SEARCH";
export const SEARCH_PENDING = "SEARCH_PENDING";
export const SEARCH_FULFILLED = "SEARCH_FULFILLED";
export const SEARCH_REJECTED = "SEARCH_REJECTED";

export const FETCH_ALL_PROFILES_PENDING = "FETCH_ALL_PROFILES_PENDING";
export const FETCH_ALL_PROFILES_FULFILLED = "FETCH_ALL_PROFILES_FULFILLED";
export const FETCH_ALL_PROFILES_REJECTED = "FETCH_ALL_PROFILES_REJECTED";
